server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306://crmssm?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
mybaits:
  type:
